### ISSUE TITLE
Race condition in IP-Ermittlung?

### ISSUE THREAD

**Issue by jannic** [johnnybee/create-supernode-BonnV2#1]
https://github.com/johnnybee/create-supernode-BonnV2/blob/cff387d14fc4e6231128d9ae24ca967b3f1210e8/roles/wireguard/files/var/www/html/wireguard.php#L6-L28

Hat dieser Code nicht eine dicke Race-Condition? Wenn zwei Clients parallel die URL abfragen, dürften sie die gleiche IP als angeblich frei zurückerhalten, oder übersehe ich etwas?

**Comment by johnnybee** [comment]
Hallo Jan,

deine Ansicht ist korrekt. In diesem Fall würden beide Clients dieselbe IP kriegen.
Dann würde über diese Verbindung kein Traffic fließen können und die Router nach 1 MInute einen neuen Versuch des Verbindungsaufbaus starten. Dies wiederholen die Router solange, bis sie Daten an den Server senden können. 
Deswegen sollte dies kein Problem sein.
